language: python
python:
  - "3.8"
env:
  - SECRET_KEY="DEBUG"

services:
  - mysql

before_script:
  - sudo mysql -e 'CREATE DATABASE employee_management;'

install:
  - python -m pip install -r employee_management/requirements.txt
  - python -m pip install coveralls
script:
  - cd employee_management/
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py test && coverage report

after_success:
  - coveralls

