language: python
python:
  - "3.8"
env:
  - SECRET_KEY='DEBUG'
  - DB_USER="root"
  - DB_NAME="employee_management"
  - DB_PASSWORD=""

services:
  - mysql

before_script:
  - sudo mysql -e 'CREATE DATABASE employee_management;'

install:
  - python -m pip install -r employee_management/requirements.txt
script:
  - python employee_management/manage.py test